// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: iidy/iidy.proto

package iidy

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	mi := &file_iidy_iidy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{0}
}

func (x *ListItem) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *ListItem) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

type AddListItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListItem      *ListItem              `protobuf:"bytes,1,opt,name=list_item,json=listItem,proto3" json:"list_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListItemRequest) Reset() {
	*x = AddListItemRequest{}
	mi := &file_iidy_iidy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListItemRequest) ProtoMessage() {}

func (x *AddListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListItemRequest.ProtoReflect.Descriptor instead.
func (*AddListItemRequest) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{1}
}

func (x *AddListItemRequest) GetListItem() *ListItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

type AddListItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int64                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListItemResponse) Reset() {
	*x = AddListItemResponse{}
	mi := &file_iidy_iidy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListItemResponse) ProtoMessage() {}

func (x *AddListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListItemResponse.ProtoReflect.Descriptor instead.
func (*AddListItemResponse) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{2}
}

func (x *AddListItemResponse) GetAdded() int64 {
	if x != nil {
		return x.Added
	}
	return 0
}

type GetListItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListItem      *ListItem              `protobuf:"bytes,1,opt,name=list_item,json=listItem,proto3" json:"list_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListItemRequest) Reset() {
	*x = GetListItemRequest{}
	mi := &file_iidy_iidy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListItemRequest) ProtoMessage() {}

func (x *GetListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListItemRequest.ProtoReflect.Descriptor instead.
func (*GetListItemRequest) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{3}
}

func (x *GetListItemRequest) GetListItem() *ListItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

type GetListItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      int32                  `protobuf:"varint,1,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListItemResponse) Reset() {
	*x = GetListItemResponse{}
	mi := &file_iidy_iidy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListItemResponse) ProtoMessage() {}

func (x *GetListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListItemResponse.ProtoReflect.Descriptor instead.
func (*GetListItemResponse) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{4}
}

func (x *GetListItemResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type IncrementListItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListItem      *ListItem              `protobuf:"bytes,1,opt,name=list_item,json=listItem,proto3" json:"list_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementListItemRequest) Reset() {
	*x = IncrementListItemRequest{}
	mi := &file_iidy_iidy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementListItemRequest) ProtoMessage() {}

func (x *IncrementListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementListItemRequest.ProtoReflect.Descriptor instead.
func (*IncrementListItemRequest) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{5}
}

func (x *IncrementListItemRequest) GetListItem() *ListItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

type IncrementListItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incremented   int64                  `protobuf:"varint,1,opt,name=incremented,proto3" json:"incremented,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementListItemResponse) Reset() {
	*x = IncrementListItemResponse{}
	mi := &file_iidy_iidy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementListItemResponse) ProtoMessage() {}

func (x *IncrementListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementListItemResponse.ProtoReflect.Descriptor instead.
func (*IncrementListItemResponse) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{6}
}

func (x *IncrementListItemResponse) GetIncremented() int64 {
	if x != nil {
		return x.Incremented
	}
	return 0
}

type DeleteListItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListItem      *ListItem              `protobuf:"bytes,1,opt,name=list_item,json=listItem,proto3" json:"list_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListItemRequest) Reset() {
	*x = DeleteListItemRequest{}
	mi := &file_iidy_iidy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListItemRequest) ProtoMessage() {}

func (x *DeleteListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteListItemRequest) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteListItemRequest) GetListItem() *ListItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

type DeleteListItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListItemResponse) Reset() {
	*x = DeleteListItemResponse{}
	mi := &file_iidy_iidy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListItemResponse) ProtoMessage() {}

func (x *DeleteListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteListItemResponse) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteListItemResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type ItemAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          string                 `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Attempts      int32                  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAttempt) Reset() {
	*x = ItemAttempt{}
	mi := &file_iidy_iidy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAttempt) ProtoMessage() {}

func (x *ItemAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAttempt.ProtoReflect.Descriptor instead.
func (*ItemAttempt) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{9}
}

func (x *ItemAttempt) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *ItemAttempt) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type AddListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListItemsRequest) Reset() {
	*x = AddListItemsRequest{}
	mi := &file_iidy_iidy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListItemsRequest) ProtoMessage() {}

func (x *AddListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListItemsRequest.ProtoReflect.Descriptor instead.
func (*AddListItemsRequest) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{10}
}

func (x *AddListItemsRequest) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *AddListItemsRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int64                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddListItemsResponse) Reset() {
	*x = AddListItemsResponse{}
	mi := &file_iidy_iidy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddListItemsResponse) ProtoMessage() {}

func (x *AddListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddListItemsResponse.ProtoReflect.Descriptor instead.
func (*AddListItemsResponse) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{11}
}

func (x *AddListItemsResponse) GetAdded() int64 {
	if x != nil {
		return x.Added
	}
	return 0
}

type GetListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	AfterItem     string                 `protobuf:"bytes,3,opt,name=after_item,json=afterItem,proto3" json:"after_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListItemsRequest) Reset() {
	*x = GetListItemsRequest{}
	mi := &file_iidy_iidy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListItemsRequest) ProtoMessage() {}

func (x *GetListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListItemsRequest.ProtoReflect.Descriptor instead.
func (*GetListItemsRequest) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{12}
}

func (x *GetListItemsRequest) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *GetListItemsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetListItemsRequest) GetAfterItem() string {
	if x != nil {
		return x.AfterItem
	}
	return ""
}

type GetListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemAttempt         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListItemsResponse) Reset() {
	*x = GetListItemsResponse{}
	mi := &file_iidy_iidy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListItemsResponse) ProtoMessage() {}

func (x *GetListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListItemsResponse.ProtoReflect.Descriptor instead.
func (*GetListItemsResponse) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{13}
}

func (x *GetListItemsResponse) GetItems() []*ItemAttempt {
	if x != nil {
		return x.Items
	}
	return nil
}

type IncrementListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementListItemsRequest) Reset() {
	*x = IncrementListItemsRequest{}
	mi := &file_iidy_iidy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementListItemsRequest) ProtoMessage() {}

func (x *IncrementListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementListItemsRequest.ProtoReflect.Descriptor instead.
func (*IncrementListItemsRequest) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{14}
}

func (x *IncrementListItemsRequest) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *IncrementListItemsRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type IncrementListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incremented   int64                  `protobuf:"varint,1,opt,name=incremented,proto3" json:"incremented,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementListItemsResponse) Reset() {
	*x = IncrementListItemsResponse{}
	mi := &file_iidy_iidy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementListItemsResponse) ProtoMessage() {}

func (x *IncrementListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementListItemsResponse.ProtoReflect.Descriptor instead.
func (*IncrementListItemsResponse) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{15}
}

func (x *IncrementListItemsResponse) GetIncremented() int64 {
	if x != nil {
		return x.Incremented
	}
	return 0
}

type DeleteListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListItemsRequest) Reset() {
	*x = DeleteListItemsRequest{}
	mi := &file_iidy_iidy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListItemsRequest) ProtoMessage() {}

func (x *DeleteListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListItemsRequest.ProtoReflect.Descriptor instead.
func (*DeleteListItemsRequest) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteListItemsRequest) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *DeleteListItemsRequest) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListItemsResponse) Reset() {
	*x = DeleteListItemsResponse{}
	mi := &file_iidy_iidy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListItemsResponse) ProtoMessage() {}

func (x *DeleteListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iidy_iidy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListItemsResponse.ProtoReflect.Descriptor instead.
func (*DeleteListItemsResponse) Descriptor() ([]byte, []int) {
	return file_iidy_iidy_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteListItemsResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_iidy_iidy_proto protoreflect.FileDescriptor

const file_iidy_iidy_proto_rawDesc = "" +
	"\n" +
	"\x0fiidy/iidy.proto\x12\x04iidy\"2\n" +
	"\bListItem\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\"A\n" +
	"\x12AddListItemRequest\x12+\n" +
	"\tlist_item\x18\x01 \x01(\v2\x0e.iidy.ListItemR\blistItem\"+\n" +
	"\x13AddListItemResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x03R\x05added\"A\n" +
	"\x12GetListItemRequest\x12+\n" +
	"\tlist_item\x18\x01 \x01(\v2\x0e.iidy.ListItemR\blistItem\"1\n" +
	"\x13GetListItemResponse\x12\x1a\n" +
	"\battempts\x18\x01 \x01(\x05R\battempts\"G\n" +
	"\x18IncrementListItemRequest\x12+\n" +
	"\tlist_item\x18\x01 \x01(\v2\x0e.iidy.ListItemR\blistItem\"=\n" +
	"\x19IncrementListItemResponse\x12 \n" +
	"\vincremented\x18\x01 \x01(\x03R\vincremented\"D\n" +
	"\x15DeleteListItemRequest\x12+\n" +
	"\tlist_item\x18\x01 \x01(\v2\x0e.iidy.ListItemR\blistItem\"2\n" +
	"\x16DeleteListItemResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\"=\n" +
	"\vItemAttempt\x12\x12\n" +
	"\x04item\x18\x01 \x01(\tR\x04item\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\x05R\battempts\"?\n" +
	"\x13AddListItemsRequest\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\",\n" +
	"\x14AddListItemsResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x03R\x05added\"`\n" +
	"\x13GetListItemsRequest\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x1d\n" +
	"\n" +
	"after_item\x18\x03 \x01(\tR\tafterItem\"?\n" +
	"\x14GetListItemsResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.iidy.ItemAttemptR\x05items\"E\n" +
	"\x19IncrementListItemsRequest\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\">\n" +
	"\x1aIncrementListItemsResponse\x12 \n" +
	"\vincremented\x18\x01 \x01(\x03R\vincremented\"B\n" +
	"\x16DeleteListItemsRequest\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\"3\n" +
	"\x17DeleteListItemsResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted2\xef\x04\n" +
	"\vIIDYService\x12B\n" +
	"\vAddListItem\x12\x18.iidy.AddListItemRequest\x1a\x19.iidy.AddListItemResponse\x12B\n" +
	"\vGetListItem\x12\x18.iidy.GetListItemRequest\x1a\x19.iidy.GetListItemResponse\x12T\n" +
	"\x11IncrementListItem\x12\x1e.iidy.IncrementListItemRequest\x1a\x1f.iidy.IncrementListItemResponse\x12K\n" +
	"\x0eDeleteListItem\x12\x1b.iidy.DeleteListItemRequest\x1a\x1c.iidy.DeleteListItemResponse\x12E\n" +
	"\fAddListItems\x12\x19.iidy.AddListItemsRequest\x1a\x1a.iidy.AddListItemsResponse\x12E\n" +
	"\fGetListItems\x12\x19.iidy.GetListItemsRequest\x1a\x1a.iidy.GetListItemsResponse\x12W\n" +
	"\x12IncrementListItems\x12\x1f.iidy.IncrementListItemsRequest\x1a .iidy.IncrementListItemsResponse\x12N\n" +
	"\x0fDeleteListItems\x12\x1c.iidy.DeleteListItemsRequest\x1a\x1d.iidy.DeleteListItemsResponseB,Z*github.com/manniwood/iidy-protobuf/pb/iidyb\x06proto3"

var (
	file_iidy_iidy_proto_rawDescOnce sync.Once
	file_iidy_iidy_proto_rawDescData []byte
)

func file_iidy_iidy_proto_rawDescGZIP() []byte {
	file_iidy_iidy_proto_rawDescOnce.Do(func() {
		file_iidy_iidy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iidy_iidy_proto_rawDesc), len(file_iidy_iidy_proto_rawDesc)))
	})
	return file_iidy_iidy_proto_rawDescData
}

var file_iidy_iidy_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_iidy_iidy_proto_goTypes = []any{
	(*ListItem)(nil),                   // 0: iidy.ListItem
	(*AddListItemRequest)(nil),         // 1: iidy.AddListItemRequest
	(*AddListItemResponse)(nil),        // 2: iidy.AddListItemResponse
	(*GetListItemRequest)(nil),         // 3: iidy.GetListItemRequest
	(*GetListItemResponse)(nil),        // 4: iidy.GetListItemResponse
	(*IncrementListItemRequest)(nil),   // 5: iidy.IncrementListItemRequest
	(*IncrementListItemResponse)(nil),  // 6: iidy.IncrementListItemResponse
	(*DeleteListItemRequest)(nil),      // 7: iidy.DeleteListItemRequest
	(*DeleteListItemResponse)(nil),     // 8: iidy.DeleteListItemResponse
	(*ItemAttempt)(nil),                // 9: iidy.ItemAttempt
	(*AddListItemsRequest)(nil),        // 10: iidy.AddListItemsRequest
	(*AddListItemsResponse)(nil),       // 11: iidy.AddListItemsResponse
	(*GetListItemsRequest)(nil),        // 12: iidy.GetListItemsRequest
	(*GetListItemsResponse)(nil),       // 13: iidy.GetListItemsResponse
	(*IncrementListItemsRequest)(nil),  // 14: iidy.IncrementListItemsRequest
	(*IncrementListItemsResponse)(nil), // 15: iidy.IncrementListItemsResponse
	(*DeleteListItemsRequest)(nil),     // 16: iidy.DeleteListItemsRequest
	(*DeleteListItemsResponse)(nil),    // 17: iidy.DeleteListItemsResponse
}
var file_iidy_iidy_proto_depIdxs = []int32{
	0,  // 0: iidy.AddListItemRequest.list_item:type_name -> iidy.ListItem
	0,  // 1: iidy.GetListItemRequest.list_item:type_name -> iidy.ListItem
	0,  // 2: iidy.IncrementListItemRequest.list_item:type_name -> iidy.ListItem
	0,  // 3: iidy.DeleteListItemRequest.list_item:type_name -> iidy.ListItem
	9,  // 4: iidy.GetListItemsResponse.items:type_name -> iidy.ItemAttempt
	1,  // 5: iidy.IIDYService.AddListItem:input_type -> iidy.AddListItemRequest
	3,  // 6: iidy.IIDYService.GetListItem:input_type -> iidy.GetListItemRequest
	5,  // 7: iidy.IIDYService.IncrementListItem:input_type -> iidy.IncrementListItemRequest
	7,  // 8: iidy.IIDYService.DeleteListItem:input_type -> iidy.DeleteListItemRequest
	10, // 9: iidy.IIDYService.AddListItems:input_type -> iidy.AddListItemsRequest
	12, // 10: iidy.IIDYService.GetListItems:input_type -> iidy.GetListItemsRequest
	14, // 11: iidy.IIDYService.IncrementListItems:input_type -> iidy.IncrementListItemsRequest
	16, // 12: iidy.IIDYService.DeleteListItems:input_type -> iidy.DeleteListItemsRequest
	2,  // 13: iidy.IIDYService.AddListItem:output_type -> iidy.AddListItemResponse
	4,  // 14: iidy.IIDYService.GetListItem:output_type -> iidy.GetListItemResponse
	6,  // 15: iidy.IIDYService.IncrementListItem:output_type -> iidy.IncrementListItemResponse
	8,  // 16: iidy.IIDYService.DeleteListItem:output_type -> iidy.DeleteListItemResponse
	11, // 17: iidy.IIDYService.AddListItems:output_type -> iidy.AddListItemsResponse
	13, // 18: iidy.IIDYService.GetListItems:output_type -> iidy.GetListItemsResponse
	15, // 19: iidy.IIDYService.IncrementListItems:output_type -> iidy.IncrementListItemsResponse
	17, // 20: iidy.IIDYService.DeleteListItems:output_type -> iidy.DeleteListItemsResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_iidy_iidy_proto_init() }
func file_iidy_iidy_proto_init() {
	if File_iidy_iidy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iidy_iidy_proto_rawDesc), len(file_iidy_iidy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iidy_iidy_proto_goTypes,
		DependencyIndexes: file_iidy_iidy_proto_depIdxs,
		MessageInfos:      file_iidy_iidy_proto_msgTypes,
	}.Build()
	File_iidy_iidy_proto = out.File
	file_iidy_iidy_proto_goTypes = nil
	file_iidy_iidy_proto_depIdxs = nil
}
