// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: iidy/iidy.proto

package iidy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IIDYService_AddListItem_FullMethodName        = "/iidy.IIDYService/AddListItem"
	IIDYService_GetListItem_FullMethodName        = "/iidy.IIDYService/GetListItem"
	IIDYService_IncrementListItem_FullMethodName  = "/iidy.IIDYService/IncrementListItem"
	IIDYService_DeleteListItem_FullMethodName     = "/iidy.IIDYService/DeleteListItem"
	IIDYService_AddListItems_FullMethodName       = "/iidy.IIDYService/AddListItems"
	IIDYService_GetListItems_FullMethodName       = "/iidy.IIDYService/GetListItems"
	IIDYService_IncrementListItems_FullMethodName = "/iidy.IIDYService/IncrementListItems"
	IIDYService_DeleteListItems_FullMethodName    = "/iidy.IIDYService/DeleteListItems"
)

// IIDYServiceClient is the client API for IIDYService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IIDYServiceClient interface {
	AddListItem(ctx context.Context, in *AddListItemRequest, opts ...grpc.CallOption) (*AddListItemResponse, error)
	GetListItem(ctx context.Context, in *GetListItemRequest, opts ...grpc.CallOption) (*GetListItemResponse, error)
	IncrementListItem(ctx context.Context, in *IncrementListItemRequest, opts ...grpc.CallOption) (*IncrementListItemResponse, error)
	DeleteListItem(ctx context.Context, in *DeleteListItemRequest, opts ...grpc.CallOption) (*DeleteListItemResponse, error)
	AddListItems(ctx context.Context, in *AddListItemsRequest, opts ...grpc.CallOption) (*AddListItemsResponse, error)
	GetListItems(ctx context.Context, in *GetListItemsRequest, opts ...grpc.CallOption) (*GetListItemsResponse, error)
	IncrementListItems(ctx context.Context, in *IncrementListItemsRequest, opts ...grpc.CallOption) (*IncrementListItemsResponse, error)
	DeleteListItems(ctx context.Context, in *DeleteListItemsRequest, opts ...grpc.CallOption) (*DeleteListItemsResponse, error)
}

type iIDYServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIIDYServiceClient(cc grpc.ClientConnInterface) IIDYServiceClient {
	return &iIDYServiceClient{cc}
}

func (c *iIDYServiceClient) AddListItem(ctx context.Context, in *AddListItemRequest, opts ...grpc.CallOption) (*AddListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddListItemResponse)
	err := c.cc.Invoke(ctx, IIDYService_AddListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iIDYServiceClient) GetListItem(ctx context.Context, in *GetListItemRequest, opts ...grpc.CallOption) (*GetListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListItemResponse)
	err := c.cc.Invoke(ctx, IIDYService_GetListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iIDYServiceClient) IncrementListItem(ctx context.Context, in *IncrementListItemRequest, opts ...grpc.CallOption) (*IncrementListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementListItemResponse)
	err := c.cc.Invoke(ctx, IIDYService_IncrementListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iIDYServiceClient) DeleteListItem(ctx context.Context, in *DeleteListItemRequest, opts ...grpc.CallOption) (*DeleteListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteListItemResponse)
	err := c.cc.Invoke(ctx, IIDYService_DeleteListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iIDYServiceClient) AddListItems(ctx context.Context, in *AddListItemsRequest, opts ...grpc.CallOption) (*AddListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddListItemsResponse)
	err := c.cc.Invoke(ctx, IIDYService_AddListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iIDYServiceClient) GetListItems(ctx context.Context, in *GetListItemsRequest, opts ...grpc.CallOption) (*GetListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListItemsResponse)
	err := c.cc.Invoke(ctx, IIDYService_GetListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iIDYServiceClient) IncrementListItems(ctx context.Context, in *IncrementListItemsRequest, opts ...grpc.CallOption) (*IncrementListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementListItemsResponse)
	err := c.cc.Invoke(ctx, IIDYService_IncrementListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iIDYServiceClient) DeleteListItems(ctx context.Context, in *DeleteListItemsRequest, opts ...grpc.CallOption) (*DeleteListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteListItemsResponse)
	err := c.cc.Invoke(ctx, IIDYService_DeleteListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IIDYServiceServer is the server API for IIDYService service.
// All implementations must embed UnimplementedIIDYServiceServer
// for forward compatibility.
type IIDYServiceServer interface {
	AddListItem(context.Context, *AddListItemRequest) (*AddListItemResponse, error)
	GetListItem(context.Context, *GetListItemRequest) (*GetListItemResponse, error)
	IncrementListItem(context.Context, *IncrementListItemRequest) (*IncrementListItemResponse, error)
	DeleteListItem(context.Context, *DeleteListItemRequest) (*DeleteListItemResponse, error)
	AddListItems(context.Context, *AddListItemsRequest) (*AddListItemsResponse, error)
	GetListItems(context.Context, *GetListItemsRequest) (*GetListItemsResponse, error)
	IncrementListItems(context.Context, *IncrementListItemsRequest) (*IncrementListItemsResponse, error)
	DeleteListItems(context.Context, *DeleteListItemsRequest) (*DeleteListItemsResponse, error)
	mustEmbedUnimplementedIIDYServiceServer()
}

// UnimplementedIIDYServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIIDYServiceServer struct{}

func (UnimplementedIIDYServiceServer) AddListItem(context.Context, *AddListItemRequest) (*AddListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddListItem not implemented")
}
func (UnimplementedIIDYServiceServer) GetListItem(context.Context, *GetListItemRequest) (*GetListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListItem not implemented")
}
func (UnimplementedIIDYServiceServer) IncrementListItem(context.Context, *IncrementListItemRequest) (*IncrementListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementListItem not implemented")
}
func (UnimplementedIIDYServiceServer) DeleteListItem(context.Context, *DeleteListItemRequest) (*DeleteListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteListItem not implemented")
}
func (UnimplementedIIDYServiceServer) AddListItems(context.Context, *AddListItemsRequest) (*AddListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddListItems not implemented")
}
func (UnimplementedIIDYServiceServer) GetListItems(context.Context, *GetListItemsRequest) (*GetListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListItems not implemented")
}
func (UnimplementedIIDYServiceServer) IncrementListItems(context.Context, *IncrementListItemsRequest) (*IncrementListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementListItems not implemented")
}
func (UnimplementedIIDYServiceServer) DeleteListItems(context.Context, *DeleteListItemsRequest) (*DeleteListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteListItems not implemented")
}
func (UnimplementedIIDYServiceServer) mustEmbedUnimplementedIIDYServiceServer() {}
func (UnimplementedIIDYServiceServer) testEmbeddedByValue()                     {}

// UnsafeIIDYServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IIDYServiceServer will
// result in compilation errors.
type UnsafeIIDYServiceServer interface {
	mustEmbedUnimplementedIIDYServiceServer()
}

func RegisterIIDYServiceServer(s grpc.ServiceRegistrar, srv IIDYServiceServer) {
	// If the following call panics, it indicates UnimplementedIIDYServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IIDYService_ServiceDesc, srv)
}

func _IIDYService_AddListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IIDYServiceServer).AddListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IIDYService_AddListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IIDYServiceServer).AddListItem(ctx, req.(*AddListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IIDYService_GetListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IIDYServiceServer).GetListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IIDYService_GetListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IIDYServiceServer).GetListItem(ctx, req.(*GetListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IIDYService_IncrementListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IIDYServiceServer).IncrementListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IIDYService_IncrementListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IIDYServiceServer).IncrementListItem(ctx, req.(*IncrementListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IIDYService_DeleteListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IIDYServiceServer).DeleteListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IIDYService_DeleteListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IIDYServiceServer).DeleteListItem(ctx, req.(*DeleteListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IIDYService_AddListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IIDYServiceServer).AddListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IIDYService_AddListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IIDYServiceServer).AddListItems(ctx, req.(*AddListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IIDYService_GetListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IIDYServiceServer).GetListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IIDYService_GetListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IIDYServiceServer).GetListItems(ctx, req.(*GetListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IIDYService_IncrementListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IIDYServiceServer).IncrementListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IIDYService_IncrementListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IIDYServiceServer).IncrementListItems(ctx, req.(*IncrementListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IIDYService_DeleteListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IIDYServiceServer).DeleteListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IIDYService_DeleteListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IIDYServiceServer).DeleteListItems(ctx, req.(*DeleteListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IIDYService_ServiceDesc is the grpc.ServiceDesc for IIDYService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IIDYService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iidy.IIDYService",
	HandlerType: (*IIDYServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddListItem",
			Handler:    _IIDYService_AddListItem_Handler,
		},
		{
			MethodName: "GetListItem",
			Handler:    _IIDYService_GetListItem_Handler,
		},
		{
			MethodName: "IncrementListItem",
			Handler:    _IIDYService_IncrementListItem_Handler,
		},
		{
			MethodName: "DeleteListItem",
			Handler:    _IIDYService_DeleteListItem_Handler,
		},
		{
			MethodName: "AddListItems",
			Handler:    _IIDYService_AddListItems_Handler,
		},
		{
			MethodName: "GetListItems",
			Handler:    _IIDYService_GetListItems_Handler,
		},
		{
			MethodName: "IncrementListItems",
			Handler:    _IIDYService_IncrementListItems_Handler,
		},
		{
			MethodName: "DeleteListItems",
			Handler:    _IIDYService_DeleteListItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iidy/iidy.proto",
}
